### ISSUE TITLE
the network can't work on raspberry pi2

### ISSUE THREAD

**Issue by shengyp0929** [Forty-Tw0/RaspberryPi-FreeRTOS#6]
Thanks for your sharing.
I have tried this on raspberry pi 2. the led task can run well. 
However, the network card seems not work. I can't ping this address through.

the network parameter in my LAN is:
       network gateway: 192.168.1.1
       Mask: 255.255.255.0

The default setting in the main.c is,
        const unsigned char ucIPAddress[ 4 ] = {192, 168, 1, 42};
	const unsigned char ucNetMask[ 4 ] = {255, 255, 255, 0};
	const unsigned char ucGatewayAddress[ 4 ] = {192, 168, 1, 1};
which should match the setting in my LAN.
I can manually set the similar IP with my Ubuntu PC.

Looking forward your help. Thanks in advance.

**Comment by Forty-Tw0** [comment]
I have just merged https://github.com/Forty-Tw0/RaspberryPi-FreeRTOS/commit/471343866f521cbcda8ce6571d03efa55bc69b5c into the "final branch", I have not really gotten around to testing it but see if it will work any better for you.
