### ISSUE TITLE
how to debug on raspberry pi2

### ISSUE THREAD

**Issue by chen0yi** [Forty-Tw0/RaspberryPi-FreeRTOS#7]
Thanks for your sharing.
As a beginner, I have some questions.
How to use the serial port to print?
Use TTL change USB or TTL change RS232?
Does it contain related drivers?
And I also can not ping the IP address.
So how to use the  net export？
Looking forward your help.

**Comment by Forty-Tw0** [comment]
- Yes, you would use USB to RS232 to attach to the pins on your Pi.
- I don't think I have included drivers for RS232, but there are several available elsewhere which you could try to port.
- I had never finished the network driver so it was not pingable, but someone has made a pull request which might work. I have not tested it, but I will assume it works.
