### ISSUE TITLE
how is the pointer value of BCM2835_GPIO_REGS* is determined

### ISSUE THREAD

**Issue by kamomil** [Forty-Tw0/RaspberryPi-FreeRTOS#8]
Hi,
I try to understand the code, I see in the file `gpio.c` the line 

`volatile BCM2835_GPIO_REGS * const pRegs = (BCM2835_GPIO_REGS *) (0x3f200000);`

How is the value `0x3f200000` decided ?

Thanks

**Comment by Forty-Tw0** [comment]
It depends on what version of the Raspberry Pi you are building for and what chipset it uses.
#define BCM2836_PERI_BASE       0x3F000000
#define GPIO_BASE               (BCM2836_PERI_BASE + 0x200000)
https://www.muddyengineer.com/2016/11/c-programming-raspberry-pi-2-gpio-driver/
